version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: inmyhead-postgres
    environment:
      POSTGRES_DB: inmyhead
      POSTGRES_USER: inmyhead_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmyhead_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inmyhead-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: inmyhead-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inmyhead-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: inmyhead-qdrant
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inmyhead-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: inmyhead-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin_CHANGE_ME
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - inmyhead-network

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  minio_data:

networks:
  inmyhead-network:
    driver: bridge
