version: 2
updates:
  # Enable version updates for npm (api-gateway)
  - package-ecosystem: "npm"
    directory: "/services/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "javascript"

  # Enable version updates for pip (document-processor)
  - package-ecosystem: "pip"
    directory: "/services/document-processor"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "python"

  # Enable version updates for pip (ai-engine)
  - package-ecosystem: "pip"
    directory: "/services/ai-engine"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "python"

  # Enable version updates for pip (search-service)
  - package-ecosystem: "pip"
    directory: "/services/search-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "python"

  # Enable version updates for pip (resource-manager)
  - package-ecosystem: "pip"
    directory: "/services/resource-manager"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "python"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "team-reviewers"
    labels:
      - "dependencies"
      - "github-actions"
